language: php
sudo: reqiured

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

install:
   - composer install
   - docker build -t mammuth/TUM.sexy .
