sudo: required
language: php

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - DOCKER_REPOSITORY=$DOCKER_USERNAME/tum.sexy

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
   - composer install

script:
  - composer test
  - docker build -t tumsexy .

before_deploy: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

deploy:
  provider: script
  script: ./.travis/dockerhub
  on:
    branch: master
    php: 7.3
