language: php

# Run tests
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

install:
   - composer install

# Build Docker image after running and passing tests
sudo: required
services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t tumsexy .