language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

before_install:
  - pecl list
  - php -i
  - printf "\n" | pecl install imagick

install:
   - composer install
