language: php

# Run tests
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: 7.3
    - php: nightly

install:
   - composer install

# Build Docker image after running and passing tests
sudo: required
services:
  - docker

script:
  - composer test
  - docker build -t tumsexy .

before_deploy: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

deploy:
  provider: script
  script: ./.travis/dockerhub
  on:
    tags: true
    php: 7.2
